stages:
  - build
  - combine

variables:
  BUILD_DIR: "tree-sitter/builds"
  GIT_SUBMODULE_STRATEGY: normal # pull just top-level submodules (tree-sitter repos)


.gitconfig: &gitconfig
  - git config --global user.email $GITLAB_USER_EMAIL
  - git config --global user.name "CI Builder"
  - git remote set-url origin https://oauth2:$CI_CD_TOKEN@gitlab.fit.cvut.cz/woowoo/lsp/woowoo-language-server.git
  - git checkout $CI_COMMIT_BRANCH
  - git fetch
  - git reset --hard $CI_COMMIT_BRANCH


# -- BUILDS:
# 
# cross-compile tree-sitter parsers (WooWoo + yaml) using Dockcross images

.build_script: &build_script
  - mkdir -p $BUILD_DIR/woowoo/ $BUILD_DIR/yaml/
  - $CC -o $BUILD_DIR/woowoo/${OS}-${ARCH}.$EXT -shared -fPIC tree-sitter/tree-sitter-woowoo/src/parser.c tree-sitter/tree-sitter-woowoo/src/scanner.cc -I./tree-sitter/tree-sitter-woowoo/src -lstdc++
  - $CC -o $BUILD_DIR/yaml/${OS}-${ARCH}.$EXT -shared -fPIC tree-sitter/tree-sitter-yaml/src/parser.c tree-sitter/tree-sitter-yaml/src/scanner.cc -I./tree-sitter/tree-sitter-yaml/src -lstdc++


build-windows-x64:
  stage: build
  image: dockcross/windows-static-x64:latest
  variables:
    OS: "windows"
    ARCH: "x64"
    EXT: "dll"
  script:
    - *build_script
  artifacts:
    untracked: true
    expire_in: 1 hour
  only:
    - web


# TODO: test
build-windows-arm64:
  stage: build
  image: dockcross/windows-arm64
  variables:
    OS: "windows"
    ARCH: "arm64"
    EXT: "dll"
  script:
    - *build_script
  artifacts:
    untracked: true
    expire_in: 1 hour
  only:
    - web


build-linux-x64:
  stage: build
  image: dockcross/linux-x64-clang
  variables:
    OS: "linux"
    ARCH: "x64"
    EXT: "so"
  script:
    - *build_script
  artifacts:
    untracked: true
    expire_in: 1 hour
  only:
    - web


# TODO: test
build-linux-arm64:
  stage: build
  image: dockcross/linux-arm64
  variables:
    OS: "linux"
    ARCH: "arm64"
    EXT: "so"
  script:
    - *build_script
  artifacts:
    untracked: true
    expire_in: 1 hour
  only:
    - web


# Commit all previously generated parsers (into new separate commit).
combine-and-commit:
  stage: combine
  script:
    - ls -la
    - ls -la $BUILD_DIR
    - ls -la $BUILD_DIR/woowoo/
    - *gitconfig
    - git add $BUILD_DIR
    - git commit -m "Generated parser binaries."
    - git push origin
  dependencies:
    - build-windows-x64
    - build-windows-arm64
    - build-linux-x64
    - build-linux-arm64
  only:
    - web
